---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-serviceaccount
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-serviceaccount
  namespace: kube-system
rules:
- apiGroups:
  - "*" 
  resources:
  - "*"  
  verbs:
  - "*"  
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-serviceaccount
roleRef:
  kind: ClusterRole
  name: k8s-serviceaccount
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: k8s-serviceaccount
  namespace: kube-system
---
# Source: Experimental/charts/k8s-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: experimental-k8s-service
  labels:
    helm.sh/chart: k8s-service-0.1.0
    app.kubernetes.io/name: k8s-service
    app.kubernetes.io/instance: experimental
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: k8s-service
    app.kubernetes.io/instance: experimental
---
# Source: Experimental/charts/k8s-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: experimental-k8s-service
  labels:
    helm.sh/chart: k8s-service-0.1.0
    app.kubernetes.io/name: k8s-service
    app.kubernetes.io/instance: experimental
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-service
      app.kubernetes.io/instance: experimental
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-service
        app.kubernetes.io/instance: experimental
    spec:
      serviceAccountName: k8s-serviceaccount
      securityContext:
        {}
      containers:
        - name: k8s-service
          securityContext:
            {}
          image: "thorstenbaek/k8s-service:v1.0.1.3"
          imagePullPolicy: Always
          env:
            - name: TARGET_DOMAIN
              value: sandbox.dips.no
            - name: IsolatedManifestTemplateURL
              value: https://raw.githubusercontent.com/thorstenbaek/k8sSandBox/master/helm/SandBox/sandboxWithDb.release.yaml
            - name: ManifestTemplateURL
              value: https://raw.githubusercontent.com/thorstenbaek/k8sSandBox/master/helm/SandBox/sandbox.release.yaml
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          resources:
            {}
---
# Source: Experimental/charts/k8s-service/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: experimental-k8s-service  
  labels:
    helm.sh/chart: k8s-service-0.1.0
    app.kubernetes.io/name: k8s-service
    app.kubernetes.io/instance: experimental
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - "k8s-service.sandbox.dips.no"
      secretName: k8s-service-experimental-tls
  rules:
    - host: "k8s-service.sandbox.dips.no"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: experimental-k8s-service
                port: 
                  number: 80